/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-5-18 下午3:17' with Gradle 2.13
 *
 * @author Administrator, @date 17-5-18 下午3:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
